name: Build Icad Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the image to build'
        required: true
        type: string

env:
   REGISTRY: ghcr.io
   ORG: cosmos
   IMAGE_NAME: ibc-go-icad
   VERSION: "${{ inputs.tag }}"

jobs:
   build-image-at-tag:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
           with:
            ref: "${{ env.VERSION }}"
            fetch-depth: 0
         - name: Log in to the Container registry
           uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
           with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
         - name: Fetch files for docker build
           run: |
            curl https://raw.githubusercontent.com/cosmos/interchain-accounts-demo/master/Dockerfile -o Dockerfile
            curl https://raw.githubusercontent.com/cosmos/interchain-accounts-demo/master/Makefile -o Makefile
         - name: Build image
           run: |
            docker build . -t "${REGISTRY}/${ORG}/${IMAGE_NAME}:${VERSION}"
            docker push "${REGISTRY}/${ORG}/${IMAGE_NAME}:${VERSION}"
